export const config = {
  formSelector: '.form',
  inputSelector: '.form__input',
  submitButtonSelector: '.form__submit',
  inactiveButtonClass: 'form__save_inactive',
  inputErrorClass: 'form__input_type_error',
  errorClass: 'form__input-error_active'
};

export const settings = {
  baseUrl: 'https://mesto.nomoreparties.co/v1/cohort36',
  clientToken: 'fcfa5c3a-c07d-49f3-a47d-0099ff285712',
  form: '.form',
  formDelete: '.form__delete',
  avatar: '.avatar',
  slideType: '.popup_type_slide',
  slideName: '.slide__name',
  slideImage: '.slide__image',
  profileName: '.profile__name',
  profileProfession: '.profile__profession',
  openPopup: 'popup_active',
  closePopup: 'popup__close',
  closeButton: '.popup__close',
  popupModal: '.popup_type_delete',
  popupTypeAdd: '.popup_type_add',
  popupTypeEdit: '.popup_type_edit',
  cardTemplate: '#card-template',
  cardName: '.element__name',
  cardLike: 'element__like_checked',
  inputName: '.form__input_type_name',
  inputProfession: '.form__input_type_profession',
  buttonSave: '.form__save',
  buttonAdd: '.profile__add',
  buttonEdit: '.profile__edit',
  editForm: '.form_type_edit',
  addForm: '.form_type_add',
  elements: '.elements',
  element: '.element',
  elementLike: '.element__like',
  elementRemove: '.element__remove',
  elementImage: '.element__image',
  elementCounter: '.element__counter'
};